name: scrape-maxmilhas

on:
  schedule:
    - cron: "*/30 * * * *"   # a cada 30 min
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: America/Sao_Paulo

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          install-chromedriver: true

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper (headless, 1 ciclo)
        run: |
          python maxmilhas_scraper_gha.py --headless --once --saida data

      - name: Commit & Push (com pull --rebase e retry)
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config pull.rebase true

          if [ -z "$(git status --porcelain data)" ]; then
            echo "Sem alterações em /data"
            exit 0
          fi

          git add data
          git commit -m "maxmilhas: $(date +'%Y-%m-%d %H:%M:%S %Z')"

          for i in 1 2 3; do
            echo "Tentativa de push #$i…"
            git pull --rebase --autostash origin "$BRANCH_NAME" || true
            if git push origin "$BRANCH_NAME"; then
              echo "Push OK"
              break
            fi
            echo "Push falhou, repetindo em 3s…"
            sleep 3
          done
