name: scrape-capo-5partes

on:
  schedule:
    - cron: "*/30 * * * *"   # ajuste como preferir
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: America/Sao_Paulo
    strategy:
      fail-fast: false
      matrix:
        grupo:
          - { nome: G1, trechos: "CGH-SDU,SDU-CGH,GRU-POA,POA-GRU" }
          - { nome: G2, trechos: "CGH-GIG,GIG-CGH,BSB-CGH,CGH-BSB" }
          - { nome: G3, trechos: "CGH-REC,REC-CGH,CGH-SSA,SSA-CGH" }
          - { nome: G4, trechos: "BSB-GIG,GIG-BSB,GIG-REC,REC-GIG" }
          - { nome: G5, trechos: "GIG-SSA,SSA-GIG,BSB-SDU,SDU-BSB" }

    concurrency:
      group: capo-${{ matrix.grupo.nome }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: browser-actions/setup-chrome@v2
        with:
          install-chromedriver: true

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run grupo ${{ matrix.grupo.nome }}
        env:
          TRECHOS_CSV: ${{ matrix.grupo.trechos }}
          ADVPS_CSV: "1,5,11,17,30"
        run: |
          python capoviagens_scraper.py

      - name: Commit artifacts
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.xlsx || true
          git commit -m "capo ${{ matrix.grupo.nome }} $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "nada a commitar"
          git push || true
