name: scrape-flipmilhas

on:
  schedule:
    - cron: "*/30 * * * *"   # a cada 30 min (UTC). 07:00 BRT = 0 10 * * *
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (na RAIZ)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper (gera output/FLIPMILHAS.xlsx na RAIZ)
        run: |
          python flipmilhas_scraper_gha.py --headless --once
          ls -lah output || true

      - name: Upload artifact (planilha)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: FLIPMILHAS-planilha
          path: output/FLIPMILHAS.xlsx

      - name: Commit cópia com timestamp em data/
        run: |
          mkdir -p data
          ts=$(date +'%Y%m%d_%H%M%S')
          cp output/FLIPMILHAS.xlsx "data/FLIPMILHAS_${ts}.xlsx"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.xlsx
          git commit -m "Atualiza FLIPMILHAS.xlsx (${ts}) [skip ci]" || echo "Sem mudanças"
          git push
