name: scrape-capoviagens

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: America/Sao_Paulo

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -la
          echo "----"
          ls -la data || true
          echo "----"
          ls -R | head -n 500

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Chrome (with Chromedriver)
        uses: browser-actions/setup-chrome@v2
        with:
          install-chromedriver: true

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install selenium webdriver-manager pandas openpyxl
          fi

      # Detecta o script em nomes/pastas comuns
      - name: Detect scraper path
        id: detect
        run: |
          set -e
          CANDIDATES="
          capoviagens_scraper.py
          scripts/capoviagens_scraper.py
          capoviagens_scraper_gha.py
          scripts/capoviagens_scraper_gha.py
          "
          FOUND=""
          for f in $CANDIDATES; do
            if [ -f "$f" ]; then
              FOUND="$f"
              break
            fi
          done
          if [ -z "$FOUND" ]; then
            echo "❌ Script não encontrado. Coloque-o na raiz como capoviagens_scraper.py ou ajuste o caminho aqui." >&2
            exit 1
          fi
          echo "SCRIPT_PATH=$FOUND" >> $GITHUB_ENV
          echo "Usando script: $FOUND"

      - name: Run scraper
        run: |
          mkdir -p data
          python "$SCRIPT_PATH"

      - name: Commit & push data (se houver mudanças)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.xlsx || true
          if ! git diff --cached --quiet; then
            git commit -m "data: CAPOVIAGENS scrape $(date -u +'%Y-%m-%d %H:%M:%S') [skip ci]"
            git push
          else
            echo "Sem mudanças para commitar."
          fi
