- name: Install deps
  run: |
    python -m pip install --upgrade pip
    pip install -r flipmilhas-scraper/requirements.txt

- name: Run scraper (1 ciclo headless)
  run: |
    python flipmilhas-scraper/flipmilhas_scraper_gha.py --headless --once

- name: Upload artifact (planilha)
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: FLIPMILHAS-planilha
    path: output/FLIPMILHAS.xlsx

- name: Commit cópia com timestamp
  run: |
    mkdir -p data
    ts=$(date +'%Y%m%d_%H%M%S')
    cp output/FLIPMILHAS.xlsx "data/FLIPMILHAS_${ts}.xlsx"
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git add data/*.xlsx
    git commit -m "Atualiza FLIPMILHAS.xlsx (${ts}) [skip ci]" || echo "Sem mudanças"
    git push
