name: scrape-flipmilhas

on:
  schedule:
    - cron: "*/30 * * * *"        # a cada 30 min
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: America/Sao_Paulo       # <<< força timestamps locais (data, hora, commits)
    concurrency:
      group: scrape-commit
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          # permite pull --rebase antes do push

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper (gera output/FLIPMILHAS.xlsx na raiz)
        run: |
          python flipmilhas_scraper_gha.py --headless --once

      - name: Commit cópia com timestamp local em data/
        run: |
          mkdir -p data
          ts=$(date +'%Y%m%d_%H%M%S')         # <<-- agora em America/Sao_Paulo
          cp output/FLIPMILHAS.xlsx "data/FLIPMILHAS_${ts}.xlsx"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          export GIT_AUTHOR_DATE="$(date -R)"      # datas do commit em horário local
          export GIT_COMMITTER_DATE="$(date -R)"
          git add data/*.xlsx
          git commit -m "Atualiza FLIPMILHAS.xlsx (${ts}) [localtime]" || echo "Sem mudanças"

      - name: Pull (rebase) e Push
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git fetch origin $BRANCH
          git pull --rebase origin $BRANCH || true
          git push origin HEAD:$BRANCH

      - name: Upload artifact (planilha)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: FLIPMILHAS-planilha
          path: output/FLIPMILHAS.xlsx
