name: scrape-capoviagens

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: America/Sao_Paulo   # garante o fuso para `date`

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          install-chromedriver: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper (headless, single cycle, filename com timestamp)
        run: |
          # Formato: CAPOVIAGENS_YYYYMMDD_HHMMSS.xlsx
          FILE="CAPOVIAGENS_$(date +%Y%m%d_%H%M%S).xlsx"
          echo "Arquivo: $FILE"
          python capoviagens_scraper_gha.py --headless --once --saida data --file "$FILE"

      - name: Commit & Push results (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain data)" ]; then
            git add data
            git commit -m "capoviagens: $(date +'%Y-%m-%d %H:%M:%S %Z')"
            git push
          else
            echo "Sem alterações em /data"
          fi
