name: scrape-capo-5partes-xls

on:
  schedule:
    - cron: "*/10 * * * *"   # a cada 10 minutos (UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: write
    env:
      TZ: America/Sao_Paulo
      PYTHONUNBUFFERED: "1"   # logs sem buffer
      CI: "true"              # ativa headless no script

    strategy:
      fail-fast: false
      matrix:
        grupo:
          - { nome: G1, trechos: "CGH-SDU,SDU-CGH,GRU-POA,POA-GRU" }
          - { nome: G2, trechos: "CGH-GIG,GIG-CGH,BSB-CGH,CGH-BSB" }
          - { nome: G3, trechos: "CGH-REC,REC-CGH,CGH-SSA,SSA-CGH" }
          - { nome: G4, trechos: "BSB-GIG,GIG-BSB,GIG-REC,REC-GIG" }
          - { nome: G5, trechos: "GIG-SSA,SSA-GIG,BSB-SDU,SDU-BSB" }

    concurrency:
      group: capo-xls-${{ matrix.grupo.nome }}
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Setup Chrome + Chromedriver
        uses: browser-actions/setup-chrome@v2
        with:
          install-chromedriver: true

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # requisitos mínimos
          pip install selenium==4.24.0 pandas==2.2.2 openpyxl==3.1.5

      - name: Run ${{ matrix.grupo.nome }}
        shell: bash
        env:
          TRECHOS_CSV: ${{ matrix.grupo.trechos }}
          ADVPS_CSV: "1,5,11,17,30"
        run: |
          set -e
          mkdir -p "data/${{ matrix.grupo.nome }}"
          # timeout controla o passo (guarda margem dentro do job de 25m)
          timeout 22m python -u scripts/capoviagens_scraper_gha.py \
            --out-dir "data/${{ matrix.grupo.nome }}" \
            --trechos "${TRECHOS_CSV}" \
            --advps "${ADVPS_CSV}" \
            --timeout 60 \
            --check-no-results 30 \
            --poll 1 \
            --pageload-timeout 30 \
            --headless

      - name: Commit only this group's files (rebase + retry)
        shell: bash
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          BRANCH="${GITHUB_REF_NAME}"

          git fetch origin "$BRANCH"
          git checkout "$BRANCH"
          git rebase "origin/$BRANCH" || git reset --hard "origin/$BRANCH"

          git add "data/${{ matrix.grupo.nome }}/" || true
          if git diff --cached --quiet; then
            echo "Sem mudanças para commit."
            exit 0
          fi

          git commit -m "CAPO ${{ matrix.grupo.nome }} XLS $(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          n=0
          until [ $n -ge 5 ]; do
            if git push origin "$BRANCH"; then
              echo "Push OK"
              break
            fi
            n=$((n+1))
            echo "Push falhou, retry $n/5..."
            git pull --rebase origin "$BRANCH" || git reset --hard "origin/$BRANCH"
            sleep $((2*n))
          done
